"""empty message

Revision ID: 31085299d0a8
Revises: 
Create Date: 2025-07-11 11:47:02.187692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31085299d0a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('idUsuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('clave', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('idUsuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tarea',
    sa.Column('idTarea', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('completada', sa.Boolean(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idTarea')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarea')
    op.drop_table('usuario')
    # ### end Alembic commands ###
